# Generated by Django 4.2.30 on 2026-05-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_child_add_cpf_rg_photo_custody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
