# Generated by Django 5.2.8 on 2026-08-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_alter_devicetoken_token_alter_devicetoken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='child',
            name='rg',
        ),
    ]
